---
- name: Include Ubuntu tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include VirtualBox tasks
  ansible.builtin.include_tasks: virtualbox.yml
  when: inventory_hostname in groups['workers_macos']
