---
- name: Install VirtualBox on MacOS
  block:
    - name: Install Homebrew
      ansible.builtin.shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Install VirtualBox
      community.general.homebrew_cask:
        name: virtualbox
        state: present

    - name: Create VM configuration
      ansible.builtin.include_tasks: virtualbox_vm_setup.yml
  when: ansible_os_family == "Darwin"
